[Job]
name = "flow"

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T02:23:19.305636Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 4904

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T02:23:19.310679Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3529780

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T02:23:22.840581Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 4311

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T02:23:22.844908Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3656

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T02:23:22.84879Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3076

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T02:23:22.851872Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3422

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T02:23:22.855301Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3368

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T02:23:22.858682Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 9993

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T02:23:22.868688Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 14590

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T02:23:22.88329Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 23420
