[Job]
name = "flow"

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-19T02:06:28.756595Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 5681

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-19T02:06:28.762386Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 324225

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-19T02:06:29.086718Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3963

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-19T02:06:29.090692Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3544

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-19T02:06:29.094417Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3604

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-19T02:06:29.098029Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3276

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-19T02:06:29.101312Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3924

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-19T02:06:29.105243Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 39430

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-19T02:06:29.144688Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 6443

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-19T02:06:29.151144Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 10041
