[Job]
name = "flow"

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-16T08:41:51.596274Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 176214

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-16T08:41:51.772525Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 2779068

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-16T08:41:54.551607Z"
stdout = """
[510] cmd err : 101,warning: /Users/zuowenjian/devspace/galaxy/orion-syspec/Cargo.toml: unused manifest key: workspace.package.name
    Checking orion-syspec v0.7.0 (/Users/zuowenjian/devspace/galaxy/orion-syspec)
error: this expression creates a reference which is immediately dereferenced by the compiler
   --> src/system/proj.rs:102:28
    |
102 |         sys_init_gitignore(&self.root_local())?;
    |                            ^^^^^^^^^^^^^^^^^^ help: change this to: `self.root_local()`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_borrow
    = note: `-D clippy::needless-borrow` implied by `-D warnings`
    = help: to override `-D warnings` add `#[allow(clippy::needless_borrow)]`

error: could not compile `orion-syspec` (lib) due to 1 previous error
"""

[Job.tasks.result.Ok]
running_time = 823510
