[Job]
name = "flow"

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-16T02:08:00.115599Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 4727

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-16T02:08:00.120469Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 1308518

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-16T02:08:01.429107Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 4083

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-16T02:08:01.433206Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3481

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-16T02:08:01.436913Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3747

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-16T02:08:01.440678Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3710

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-16T02:08:01.444396Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 6764

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-16T02:08:01.451169Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 29677

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-16T02:08:01.480859Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 24169

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-16T02:08:01.505042Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 35140
