[Job]
name = "flow"

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-16T02:49:10.911268Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 5098

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-16T02:49:10.916508Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3112214

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-16T02:49:14.028862Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3540

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-16T02:49:14.032413Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 2977

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-16T02:49:14.035603Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 2968

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-16T02:49:14.038578Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 2778

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-16T02:49:14.041363Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3607

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-16T02:49:14.044977Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 9934

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-16T02:49:14.05492Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 8960

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-16T02:49:14.063891Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 25494
