[Job]
name = "flow"

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T03:54:02.23738Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 5086

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T03:54:02.242643Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 128753

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T03:54:02.371512Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3732

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T03:54:02.375253Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3374

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T03:54:02.378848Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3091

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T03:54:02.381947Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3365

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T03:54:02.385319Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3195

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T03:54:02.388521Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 17868

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T03:54:02.406401Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 29487

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T03:54:02.435901Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 26690
