[Job]
name = "flow"

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T03:53:58.203871Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 5179

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T03:53:58.209216Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 1293701

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T03:53:59.50307Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3936

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T03:53:59.507024Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3380

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T03:53:59.510629Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3227

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T03:53:59.513865Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 2962

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T03:53:59.516832Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3737

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T03:53:59.520582Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 11310

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T03:53:59.531904Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 12102

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T03:53:59.544017Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 32259
