[Job]
name = "flow"

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T06:30:10.880683Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 5091

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T06:30:10.885924Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 195878

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T06:30:11.081894Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 4364

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T06:30:11.086266Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3231

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T06:30:11.089721Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 2948

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T06:30:11.092677Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3390

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T06:30:11.096077Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3218

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T06:30:11.099303Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 6563

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T06:30:11.105877Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 6550

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T06:30:11.112439Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 12141
