[Job]
name = "flow"

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-19T02:05:00.52931Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 4865

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-19T02:05:00.534326Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 136153

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-19T02:05:00.670602Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 4226

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-19T02:05:00.674835Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3334

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-19T02:05:00.678387Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3531

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-19T02:05:00.681937Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 2958

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-19T02:05:00.684902Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3161

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-19T02:05:00.688071Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 10466

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-19T02:05:00.698551Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 11504

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-19T02:05:00.710068Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 22554
