[Job]
name = "flow"

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T04:38:45.822097Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 15247

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T04:38:45.837357Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 4331167
