[Job]
name = "flow"

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T02:48:44.607742Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 5543

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T02:48:44.613433Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3489145

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T02:48:48.102708Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3974

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T02:48:48.106691Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3175

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T02:48:48.110102Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 2957

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T02:48:48.113065Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3170

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T02:48:48.116242Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3220

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T02:48:48.119469Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 39685

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T02:48:48.159166Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 13539

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T02:48:48.172718Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 23202
