[Job]
name = "flow"

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-16T02:14:57.873089Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 4984

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-16T02:14:57.87821Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 1264954

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-16T02:14:59.143269Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3846

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-16T02:14:59.147124Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3265

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-16T02:14:59.150646Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3318

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-16T02:14:59.153971Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3157

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-16T02:14:59.157134Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3646

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-16T02:14:59.16079Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 23563

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-16T02:14:59.184364Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 23704

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-16T02:14:59.208082Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 25446
