[Job]
name = "flow"

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-14T11:03:52.858894Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 5213

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-14T11:03:52.864637Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 133836

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-14T11:03:52.998968Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 4210

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-14T11:03:53.003203Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 4342

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-14T11:03:53.009007Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3998

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-14T11:03:53.013027Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 4382

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-14T11:03:53.017437Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 5261

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-14T11:03:53.022734Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 15426

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-14T11:03:53.038197Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 18955

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-14T11:03:53.057189Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 54670
