[Job]
name = "flow"

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-16T02:17:12.532358Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 5070

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-16T02:17:12.537568Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 1072023

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-16T02:17:13.609694Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3738

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-16T02:17:13.61344Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3466

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-16T02:17:13.617084Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3158

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-16T02:17:13.620248Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3241

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-16T02:17:13.623498Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3297

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-16T02:17:13.626802Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 22672

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-16T02:17:13.649488Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 24593

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-16T02:17:13.674094Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 20976
