[Job]
name = "flow"

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-16T08:42:01.974809Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 159116

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-16T08:42:02.133939Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 2336913

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-16T08:42:04.470871Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 870591
