[Job]
name = "flow"

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-13T09:35:25.12986Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3958

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-13T09:35:25.133972Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 500000

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-13T09:35:25.634122Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3806

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-13T09:35:25.637939Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3357

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-13T09:35:25.641601Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3810

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-13T09:35:25.645426Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3578

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-13T09:35:25.649017Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 4139

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-13T09:35:25.653171Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 18600

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-13T09:35:25.671873Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 15297

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-13T09:35:25.687192Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 26493
