[Job]
name = "flow"

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T03:02:54.781688Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 6356

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T03:02:54.788186Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3893031

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T03:02:58.681393Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3904

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T03:02:58.685303Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3209

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T03:02:58.688675Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3310

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T03:02:58.691998Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3166

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T03:02:58.695176Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 4036

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T03:02:58.699219Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 16775

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T03:02:58.716007Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 26751

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T03:02:58.74277Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 57517
