[Job]
name = "flow"

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T02:48:37.127952Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 5550

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T02:48:37.133593Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 2190148

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T02:48:39.323907Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 11271

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T02:48:39.335193Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3193

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T02:48:39.338591Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3137

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T02:48:39.341743Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3168

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T02:48:39.344918Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 7524

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T02:48:39.352455Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 21083

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T02:48:39.373552Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 32845

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T02:48:39.40641Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 64792
