[Job]
name = "flow"

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T02:23:10.171676Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 5286

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T02:23:10.177043Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3708841

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T02:23:13.886023Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 8668

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T02:23:13.894708Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3398

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T02:23:13.898302Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3125

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T02:23:13.901434Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3119

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T02:23:13.904567Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 5351

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T02:23:13.909934Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 17124

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T02:23:13.927071Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 26524

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T02:23:13.953608Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 56491
