[Job]
name = "flow"

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-19T02:29:36.382677Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 5749

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-19T02:29:36.388568Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3438886

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-19T02:29:39.827599Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 4051

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-19T02:29:39.831663Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3375

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-19T02:29:39.835261Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3152

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-19T02:29:39.83842Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3262

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-19T02:29:39.84169Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3933

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-19T02:29:39.84563Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 39919

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-19T02:29:39.885561Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 7186

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-19T02:29:39.892758Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 11804
