[Job]
name = "flow"

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-19T02:04:45.53542Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 6045

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-19T02:04:45.541638Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 1822458

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-19T02:04:47.364249Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 5244

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-19T02:04:47.369507Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3492

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-19T02:04:47.373238Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3155

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-19T02:04:47.376408Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3298

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-19T02:04:47.379718Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3844

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-19T02:04:47.38357Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 15899

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-19T02:04:47.399478Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 11980

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-19T02:04:47.411475Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 42705
