[Job]
name = "flow"

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T04:30:33.689776Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 4841

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T04:30:33.694764Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 1199558

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T04:30:34.894461Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3721

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T04:30:34.898196Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3163

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T04:30:34.901549Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3155

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T04:30:34.90471Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3074

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T04:30:34.907796Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3757

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T04:30:34.911569Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 25164

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T04:30:34.936769Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 25101

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T04:30:34.961884Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 21421
