[Job]
name = "flow"

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-13T06:04:25.412012Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 5840

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-13T06:04:25.418359Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 2540976

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-13T06:04:27.959827Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3989

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-13T06:04:27.963837Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3469

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-13T06:04:27.968426Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3554

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-13T06:04:27.971996Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3408

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-13T06:04:27.975419Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 9135

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-13T06:04:27.984576Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 29311

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-13T06:04:28.013925Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 29155

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-13T06:04:28.043114Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 52757
