[Job]
name = "flow"

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T04:30:36.110183Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 5429

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T04:30:36.11576Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 2989489

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T04:30:39.105383Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3831

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T04:30:39.109229Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3257

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T04:30:39.112715Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3152

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T04:30:39.115872Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3065

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T04:30:39.118951Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3252

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T04:30:39.12221Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 10753

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T04:30:39.132974Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 15512

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T04:30:39.148501Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 11705
