[Job]
name = "flow"

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-16T02:10:49.707706Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 4973

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-16T02:10:49.712837Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 1046828

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-16T02:10:50.759763Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3882

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-16T02:10:50.763655Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3120

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-16T02:10:50.766988Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3100

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-16T02:10:50.770096Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3157

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-16T02:10:50.773263Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3315

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-16T02:10:50.776585Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 21703

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-16T02:10:50.798301Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 23285

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-16T02:10:50.821598Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 21538
