[Job]
name = "flow"

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-15T07:51:29.304482Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 5406

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-15T07:51:29.309985Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 2246665

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-15T07:51:31.556802Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 4066

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-15T07:51:31.560886Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3212

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-15T07:51:31.564269Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 2984

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-15T07:51:31.56726Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 2815

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-15T07:51:31.570081Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3645

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-15T07:51:31.57374Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 10078

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-15T07:51:31.583829Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 11238

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-15T07:51:31.59508Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 31719

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-15T07:51:31.626912Z"
stdout = """

running 81 tests
test addr::git::tests::test_checkout_specific_branch ... ok
test addr::git::tests::test_git_addr_pull_2 ... ok
test addr::git::tests::test_git_addr_update_local ... ignored, need more time
test addr::git::tests::test_git_addr_update_local_sub ... ok
test addr::http::tests2::test_get_filename_with_empty_path ... ok
test addr::http::tests2::test_get_filename_with_encoded_characters ... ok
test addr::http::tests2::test_get_filename_with_fragment ... ok
test addr::http::tests2::test_get_filename_with_invalid_url ... ok
test addr::http::tests2::test_get_filename_with_multiple_path_segments ... ok
test addr::http::tests2::test_get_filename_with_query_params ... ok
test addr::http::tests2::test_get_filename_with_regular_url ... ok
test addr::http::tests2::test_get_filename_with_trailing_slash ... ok
test addr::http::tests::test_http_addr ... ignored, need more time
test addr::http::tests::test_http_auth_download ... ok
test addr::http::tests::test_http_upload_post ... ok
test addr::http::tests::test_http_upload_put ... ok
test addr::local::tests::test_local ... ok
test addr::local::tests::test_rename_path_dir_new_target ... ok
test addr::local::tests::test_rename_path_dir_overwrite_existing_dir ... ok
test addr::local::tests::test_rename_path_file_new_target ... ok
test addr::local::tests::test_rename_path_file_overwrite_existing_file ... ok
test app_mod::app::tests::test_mod_cust_prj_running ... ok
test app_mod::example::tests::test_make_mod_cust_example ... ok
test conf::tests::test_async_update ... ok
test conf::tests::test_conf_file_creation ... ok
test conf::tests::test_conf_spec_new ... ok
test conf::tests::test_conf_with_addr_addr ... ok
test conf::tests::test_conf_with_http_addr ... ok
test module::depend::tests::test_depend ... ok
test module::depend::tests::test_serialize_to_yaml ... ok
test module::localize::tests::test_excluded_files ... ok
test module::localize::tests::test_helm_nginx_rendering ... ok
test module::localize::tests::test_render_directory ... ok
test module::localize::tests::test_render_path_with_handlebars ... ok
test module::setting::export::tests::test_setting_serialization ... ok
test module::setting::path::tests::test_exclude_mut ... ok
test module::setting::path::tests::test_is_exclude ... ok
test module::setting::path::tests::test_is_include ... ok
test module::setting::path::tests::test_new ... ok
test module::setting::path::tests::test_wildcard_exclude ... ok
test module::setting::path::tests::test_wildcard_include ... ok
test module::spec::test::build_mod_example ... ok
test resource::tests::test_resource_node_creation ... ok
test resource::tests::test_resource_node_save_load ... ok
test software::tests::confspec_save_load ... ok
test software::tests::software_save_load ... ok
test software::tests::test_conf_spec_creation ... ok
test system::spec::tests::build_example_sys_spec ... ok
test tools::test_get_last_segment ... ok
test tpl::comment::rust::tests::test_comment ... ok
test tpl::comment::rust::tests::test_comment_in_string ... ok
test tpl::comment::rust::tests::test_complex_mixed_case1 ... ok
test tpl::comment::rust::tests::test_complex_mixed_case2 ... ok
test tpl::comment::rust::tests::test_empty_string ... ok
test tpl::comment::rust::tests::test_mixed_comments_and_code ... ok
test tpl::comment::rust::tests::test_multi_line_comment ... ok
test tpl::comment::rust::tests::test_only_code ... ok
test tpl::comment::rust::tests::test_only_comments ... ok
test tpl::comment::rust::tests::test_only_data ... ok
test tpl::comment::rust::tests::test_only_raw_data ... ok
test tpl::comment::yml::tests::test_case1 ... ok
test tpl::comment::yml::tests::test_case2 ... ok
test tpl::comment::yml::tests::test_case4 ... ok
test tpl::comment::yml::tests::test_case5 ... ok
test tpl::comment::yml::tests::test_case6 ... ok
test tpl::comment::yml::tests::test_case7 ... ok
test tpl::covert::tests::test_convert_code_only ... ok
test tpl::covert::tests::test_convert_comment_only ... ok
test tpl::covert::tests::test_convert_hash_comment ... ok
test tpl::covert::tests::test_convert_mixed ... ok
test vars::collection::tests::test_merge_vars ... ok
test vars::collection::tests::test_toml_serialization ... ok
test vars::constraint::tests::test_value_constraint_deserialization ... ok
test vars::constraint::tests::test_value_constraint_serialization ... ok
test vars::dict::tests::test_dict_toml_serialization ... ok
test vars::types::tests::test_vartype_toml_deserialization ... ok
test vars::types::tests::test_vartype_toml_serialization ... ok
test vars::types::tests::vartype_display ... ok
test workflow::act::tests::test_host_tpl_init ... ok
test workflow::act::tests::test_k8s_tpl_init ... ok
test workflow::act::tests::test_save_and_load_actions ... ok

test result: ok. 79 passed; 0 failed; 2 ignored; 0 measured; 0 filtered out; finished in 2.09s


running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s


running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s


running 4 tests
test cond::tests::test_compare_ge ... ok
test cond::tests::test_compare_we ... ok
test cond::tests::test_eq_f64 ... ok
test cond::tests::test_eq_u32 ... ok

test result: ok. 4 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s


running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s


running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s


running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s


running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

"""

[Job.tasks.result.Ok]
running_time = 5238724
