[Job]
name = "flow"

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-16T02:49:31.227635Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 5420

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-16T02:49:31.233213Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3142872

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-16T02:49:34.376226Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 4013

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-16T02:49:34.380255Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3171

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-16T02:49:34.383596Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3187

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-16T02:49:34.386789Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 2959

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-16T02:49:34.389754Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3753

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-16T02:49:34.393515Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 9439

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-16T02:49:34.402972Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 10710

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-16T02:49:34.413699Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 13220
