[Job]
name = "flow"

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-16T02:04:48.996831Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 5717

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-16T02:04:49.002705Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 120625

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-16T02:04:49.123419Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3768

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-16T02:04:49.127195Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3184

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-16T02:04:49.130563Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3517

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-16T02:04:49.134091Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3091

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-16T02:04:49.137189Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3687

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-16T02:04:49.140883Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 16486

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-16T02:04:49.15738Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 24778

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-16T02:04:49.182173Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 62983
