[Job]
name = "flow"

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-13T10:35:14.731519Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 17452

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-13T10:35:14.749016Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3780021
