[Job]
name = "flow"

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-19T02:37:20.21952Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 5142

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-19T02:37:20.224767Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 1865438

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-19T02:37:22.09037Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 4051

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-19T02:37:22.094431Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3028

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-19T02:37:22.097641Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3152

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-19T02:37:22.100809Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 2882

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-19T02:37:22.103698Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3421

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-19T02:37:22.107128Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 10741

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-19T02:37:22.117881Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 11428

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-19T02:37:22.12932Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 33897
