[Job]
name = "flow"

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T10:17:17.92268Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 5338

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T10:17:17.928181Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 2069286

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T10:17:19.997635Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 4292

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T10:17:20.001936Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3265

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T10:17:20.005432Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3376

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T10:17:20.008824Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3243

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T10:17:20.012073Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3404

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T10:17:20.015485Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 10226

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T10:17:20.025723Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 11162

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T10:17:20.036899Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 35428
