[Job]
name = "flow"

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-13T06:10:51.268526Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 4384

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-13T06:10:51.27345Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3486317

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-13T06:10:54.760255Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 4967

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-13T06:10:54.765243Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3335

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-13T06:10:54.769614Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3356

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-13T06:10:54.772991Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3116

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-13T06:10:54.77612Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3655

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-13T06:10:54.779791Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 8802

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-13T06:10:54.788633Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 14477

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-13T06:10:54.80314Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 18337
