[Job]
name = "flow"

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T03:41:48.454821Z"
stdout = """

running 1 test
render ./example/sys-model-spec/example_sys/mods/redis_mock/arm-mac14-host/spec/res.yml ---> ./example/sys-model-spec/example_sys/mods/redis_mock/arm-mac14-host/local/res.yml
render ./example/sys-model-spec/example_sys/mods/redis_mock/arm-mac14-host/spec/artifact.yml ---> ./example/sys-model-spec/example_sys/mods/redis_mock/arm-mac14-host/local/artifact.yml
render ./example/sys-model-spec/example_sys/mods/redis_mock/arm-mac14-host/spec/logs.yml ---> ./example/sys-model-spec/example_sys/mods/redis_mock/arm-mac14-host/local/logs.yml
render ./example/sys-model-spec/example_sys/mods/redis_mock/arm-mac14-host/spec/depends.yml ---> ./example/sys-model-spec/example_sys/mods/redis_mock/arm-mac14-host/local/depends.yml
render ./example/sys-model-spec/example_sys/mods/mysql_mock/arm-mac14-host/spec/res.yml ---> ./example/sys-model-spec/example_sys/mods/mysql_mock/arm-mac14-host/local/res.yml
render ./example/sys-model-spec/example_sys/mods/mysql_mock/arm-mac14-host/spec/artifact.yml ---> ./example/sys-model-spec/example_sys/mods/mysql_mock/arm-mac14-host/local/artifact.yml
render ./example/sys-model-spec/example_sys/mods/mysql_mock/arm-mac14-host/spec/logs.yml ---> ./example/sys-model-spec/example_sys/mods/mysql_mock/arm-mac14-host/local/logs.yml
render ./example/sys-model-spec/example_sys/mods/mysql_mock/arm-mac14-host/spec/depends.yml ---> ./example/sys-model-spec/example_sys/mods/mysql_mock/arm-mac14-host/local/depends.yml
test system::spec::tests::build_example_sys_spec ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 95 filtered out; finished in 0.03s


running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s


running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

"""

[Job.tasks.result.Ok]
running_time = 7156106
