[Job]
name = "flow"

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T09:52:06.700603Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 5076

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T09:52:06.705831Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3399413

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T09:52:10.10537Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 4116

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T09:52:10.109501Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3233

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T09:52:10.112907Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3200

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T09:52:10.116119Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3020

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T09:52:10.119146Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3526

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T09:52:10.122686Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 6192

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T09:52:10.128888Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 6955

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T09:52:10.135856Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 11052
