[Job]
name = "flow"

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T04:00:54.023811Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 4956

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T04:00:54.02891Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3079504

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T04:00:57.108541Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3814

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T04:00:57.112364Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3497

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T04:00:57.116033Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3377

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T04:00:57.119418Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3120

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T04:00:57.122546Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3463

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T04:00:57.126017Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 7167

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T04:00:57.133195Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 14231

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T04:00:57.147439Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 12506
