[Job]
name = "flow"

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T04:27:18.226468Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 4881

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T04:27:18.231487Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3519000

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T04:27:21.750618Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3930

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T04:27:21.754566Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3301

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T04:27:21.758052Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3461

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T04:27:21.761527Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3350

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T04:27:21.76489Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3464

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T04:27:21.768363Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 7412

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T04:27:21.775786Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 15250

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T04:27:21.791048Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 26494
