[Job]
name = "flow"

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-15T15:13:23.329183Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 5688

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-15T15:13:23.334989Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 895685

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-15T15:13:24.230826Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3948

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-15T15:13:24.234782Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3353

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-15T15:13:24.238335Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3041

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-15T15:13:24.241383Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3034

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-15T15:13:24.244423Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3654

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-15T15:13:24.248083Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 9829

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-15T15:13:24.257923Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 10422

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-15T15:13:24.268356Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 30370
