[Job]
name = "flow"

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-19T02:37:31.544734Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 4768

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-19T02:37:31.549656Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3289105

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-19T02:37:34.838893Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3786

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-19T02:37:34.842692Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3083

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-19T02:37:34.845947Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3223

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-19T02:37:34.849179Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3254

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-19T02:37:34.85244Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3294

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-19T02:37:34.855742Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 39158

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-19T02:37:34.894912Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 6955

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-19T02:37:34.901878Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 12088
