[Job]
name = "flow"

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T03:45:42.3724Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3129

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T03:45:42.375639Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3340399

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T03:45:45.716174Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 4308

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T03:45:45.720494Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3240

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T03:45:45.72397Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3028

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T03:45:45.727004Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3067

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T03:45:45.730079Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3773

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T03:45:45.733858Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 6073

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T03:45:45.739941Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 6287

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T03:45:45.746236Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 12358
