[Job]
name = "flow"

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-19T02:04:54.225908Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 5098

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-19T02:04:54.231156Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3940597

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-19T02:04:58.171908Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 4955

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-19T02:04:58.176869Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3418

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-19T02:04:58.180541Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3058

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-19T02:04:58.183606Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3098

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-19T02:04:58.186717Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3847

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-19T02:04:58.19057Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 39075

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-19T02:04:58.229657Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 6659

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-19T02:04:58.236327Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 11208
