[Job]
name = "flow"

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-13T06:10:43.915189Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 5089

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-13T06:10:43.920795Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 122949

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-13T06:10:44.044173Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 4055

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-13T06:10:44.048247Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3315

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-13T06:10:44.052553Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3887

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-13T06:10:44.056462Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3910

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-13T06:10:44.060386Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 4123

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-13T06:10:44.064531Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 15615

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-13T06:10:44.080172Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 24330

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-13T06:10:44.104535Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 25605
