[Job]
name = "flow"

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T03:54:03.15824Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 4293

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T03:54:03.162698Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3278415

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T03:54:06.44124Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 4325

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T03:54:06.445581Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3020

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T03:54:06.448818Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 2997

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T03:54:06.451822Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3096

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T03:54:06.454926Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3329

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T03:54:06.458262Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 5905

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T03:54:06.46419Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 6559

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T03:54:06.47076Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 9759
