[Job]
name = "flow"

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T06:09:00.105211Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 5335

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T06:09:00.110649Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3893052

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T06:09:04.003857Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3666

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T06:09:04.007534Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3460

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T06:09:04.011226Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3141

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T06:09:04.014378Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3187

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T06:09:04.017572Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3439

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T06:09:04.02102Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 6624

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T06:09:04.027654Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 6762

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T06:09:04.034427Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 11957
