[Job]
name = "flow"

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-19T02:30:04.631171Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 5002

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-19T02:30:04.636316Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 126188

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-19T02:30:04.762644Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3758

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-19T02:30:04.76642Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3392

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-19T02:30:04.770018Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3053

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-19T02:30:04.773078Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3092

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-19T02:30:04.776178Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3146

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-19T02:30:04.77933Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 10699

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-19T02:30:04.790044Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 12165

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-19T02:30:04.802229Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 25385
