[Job]
name = "flow"

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T02:50:20.785573Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 4049

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T02:50:20.789741Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 2895578

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T02:50:23.685444Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3784

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T02:50:23.689239Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3212

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T02:50:23.692682Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3194

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T02:50:23.695885Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3103

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T02:50:23.698995Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3453

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T02:50:23.702456Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 7538

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T02:50:23.710008Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 15361

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T02:50:23.725381Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 8354
