[Job]
name = "flow"

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T04:58:57.158892Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 13627

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T04:58:57.172532Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3874715
