[Job]
name = "flow"

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T03:54:10.482714Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 5587

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T03:54:10.488483Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 130680

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T03:54:10.61927Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 4100

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T03:54:10.623381Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3213

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T03:54:10.626783Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3158

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T03:54:10.629947Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 2997

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T03:54:10.632952Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3026

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T03:54:10.635984Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 6085

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T03:54:10.642092Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 6826

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T03:54:10.648932Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 8179
