[Job]
name = "flow"

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T09:52:28.892961Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 5287

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T09:52:28.898385Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 132140

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T09:52:29.030692Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3999

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T09:52:29.034701Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3330

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T09:52:29.03822Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 2964

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T09:52:29.041192Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3238

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T09:52:29.044436Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3387

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T09:52:29.04783Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 6168

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T09:52:29.054008Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 6746

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T09:52:29.060777Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 9360
