[Job]
name = "flow"

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-19T02:29:44.847089Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 5038

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-19T02:29:44.852294Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 1810558

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-19T02:29:46.663007Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 4374

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-19T02:29:46.667399Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3191

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-19T02:29:46.670806Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3337

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-19T02:29:46.67415Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3077

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-19T02:29:46.677233Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3595

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-19T02:29:46.680834Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 9970

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-19T02:29:46.690819Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 11368

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-19T02:29:46.702198Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 34225
