[Job]
name = "flow"

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T04:27:14.864059Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 5015

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T04:27:14.86921Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 1779589

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T04:27:16.648987Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 9365

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T04:27:16.658366Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3290

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T04:27:16.661903Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3193

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T04:27:16.66511Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3219

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T04:27:16.668337Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 7964

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T04:27:16.676308Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 17023

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T04:27:16.693344Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 25291

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T04:27:16.718649Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 58192
