[Job]
name = "flow"

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T04:57:15.648387Z"
stdout = """
[510] cmd err : 128,fatal: tag 'v0.7.3' already exists
"""

[Job.tasks.result.Ok]
running_time = 12698

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T04:57:15.661097Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 4052817
