[Job]
name = "flow"

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-13T06:02:22.069084Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 164687

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-13T06:02:22.233817Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 2215549

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-13T06:02:24.449404Z"
stdout = """
[510] cmd err : 101,warning: /Users/zuowenjian/devspace/galaxy/orion-syspec/Cargo.toml: unused manifest key: workspace.package.name
    Checking orion_common v0.4.1 (/Users/zuowenjian/devspace/galaxy/orion-syspec/crates/orion_common)
    Checking orion_infra v0.1.0 (/Users/zuowenjian/devspace/galaxy/orion-syspec/crates/orion_infra)
    Checking orion-syspec v0.6.2 (/Users/zuowenjian/devspace/galaxy/orion-syspec)
error: this expression creates a reference which is immediately dereferenced by the compiler
  --> app/ds-mod/spec.rs:69:25
   |
69 |             spec.update(&options).await.err_conv()?;
   |                         ^^^^^^^^ help: change this to: `options`
   |
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_borrow
   = note: `-D clippy::needless-borrow` implied by `-D warnings`
   = help: to override `-D warnings` add `#[allow(clippy::needless_borrow)]`

error: could not compile `orion-syspec` (bin "ds-mod") due to 1 previous error
"""

[Job.tasks.result.Ok]
running_time = 1473217
