[Job]
name = "flow"

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-12T07:01:00.253896Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 5247

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-12T07:01:00.259288Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3849803

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-12T07:01:04.109207Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 4728

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-12T07:01:04.113945Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3212

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-12T07:01:04.11735Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3333

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-12T07:01:04.12069Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3150

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-12T07:01:04.123848Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3765

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-12T07:01:04.12762Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 8011

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-12T07:01:04.135646Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 14089

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-12T07:01:04.149748Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 19712
