[Job]
name = "flow"

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T03:07:36.016818Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 5087

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T03:07:36.022092Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3645842

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T03:07:39.66806Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3986

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T03:07:39.672054Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3284

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T03:07:39.675547Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3014

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T03:07:39.678574Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3061

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T03:07:39.681643Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3788

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T03:07:39.685439Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 6859

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T03:07:39.692313Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 17440

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T03:07:39.709764Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 18032
