[Job]
name = "flow"

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-13T09:34:01.16004Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 4614

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-13T09:34:01.164821Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 576447

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-13T09:34:01.741401Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3678

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-13T09:34:01.745099Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3141

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-13T09:34:01.748572Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3726

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-13T09:34:01.752325Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3909

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-13T09:34:01.756254Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3676

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-13T09:34:01.759946Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 10282

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-13T09:34:01.770246Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 11608

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-13T09:34:01.781874Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 31942
