[Job]
name = "flow"

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-16T02:13:19.600917Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 4978

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-16T02:13:19.606Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 141389

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-16T02:13:19.74748Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3667

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-16T02:13:19.751156Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3856

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-16T02:13:19.755191Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3237

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-16T02:13:19.758437Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3242

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-16T02:13:19.761688Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3383

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-16T02:13:19.765079Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 16567

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-16T02:13:19.781658Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 25442

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-16T02:13:19.807111Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 32107
