[Job]
name = "flow"

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T10:22:57.126432Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 4951

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T10:22:57.131475Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 130494

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T10:22:57.262228Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3786

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T10:22:57.266033Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3634

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T10:22:57.26984Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3359

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T10:22:57.273216Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3249

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T10:22:57.276473Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 4358

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T10:22:57.280841Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 10651

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T10:22:57.291502Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 11706

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T10:22:57.303223Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 20998
