[Job]
name = "flow"

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-13T09:38:33.202346Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 5918

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-13T09:38:33.208454Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 751754

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-13T09:38:33.960369Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3532

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-13T09:38:33.963917Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3615

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-13T09:38:33.967849Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3500

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-13T09:38:33.971369Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3231

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-13T09:38:33.974617Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 4771

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-13T09:38:33.979407Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 10279

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-13T09:38:33.989703Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 11162

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-13T09:38:34.000905Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 32018
