[Job]
name = "flow"

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T06:12:04.931851Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 5458

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T06:12:04.937469Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 275775

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T06:12:05.213377Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3813

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T06:12:05.217202Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 4424

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T06:12:05.221835Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3466

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T06:12:05.225312Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3621

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T06:12:05.228941Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3994

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T06:12:05.232942Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 6342

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T06:12:05.239293Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 7075

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T06:12:05.246379Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 8363
