[Job]
name = "flow"

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T06:17:33.19059Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 5859

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T06:17:33.196634Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3288245

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T06:17:36.485034Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3764

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T06:17:36.488812Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3248

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T06:17:36.492245Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3038

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T06:17:36.495289Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 2953

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T06:17:36.49825Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3393

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T06:17:36.50165Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 5947

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T06:17:36.507606Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 6439

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T06:17:36.514058Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 10498
