[Job]
name = "flow"

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T03:54:05.710003Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 5217

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T03:54:05.715319Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3573871

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T03:54:09.28934Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 5109

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T03:54:09.294467Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 4290

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T03:54:09.299015Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3899

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T03:54:09.302926Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3790

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T03:54:09.30673Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 4271

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T03:54:09.311017Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 10699

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T03:54:09.321742Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 16147

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T03:54:09.337902Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 23912
