[Job]
name = "flow"

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-15T16:34:51.844409Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 6848

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-15T16:34:51.851409Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 425452

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-15T16:34:52.277022Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 4313

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-15T16:34:52.281348Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3610

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-15T16:34:52.285154Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3735

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-15T16:34:52.288899Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3649

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-15T16:34:52.292561Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 4959

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-15T16:34:52.297529Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 12844

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-15T16:34:52.310385Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 16560

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-15T16:34:52.326958Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 52167
