[Job]
name = "flow"

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T04:00:20.386943Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 5092

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T04:00:20.392127Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3098050

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T04:00:23.490301Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3639

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T04:00:23.493955Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 2997

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T04:00:23.497166Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3169

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T04:00:23.500342Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3031

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T04:00:23.503379Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3704

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T04:00:23.50709Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 8329

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T04:00:23.515428Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 15746

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T04:00:23.531185Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 12726
