[Job]
name = "flow"

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-16T02:34:59.47086Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 5371

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-16T02:34:59.47639Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 4968763

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-16T02:35:04.445272Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3680

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-16T02:35:04.44896Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3050

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-16T02:35:04.452173Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3055

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-16T02:35:04.455236Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 2885

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-16T02:35:04.45813Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3936

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-16T02:35:04.462075Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 8283

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-16T02:35:04.470366Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 10692

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-16T02:35:04.481069Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 23943
