[Job]
name = "flow"

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T03:45:38.224018Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 5122

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T03:45:38.229293Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 1189561

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T03:45:39.418986Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 4097

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T03:45:39.423092Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3126

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T03:45:39.426445Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3078

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T03:45:39.42953Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3096

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T03:45:39.432634Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3590

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T03:45:39.436231Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 10673

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T03:45:39.446932Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 11573

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T03:45:39.458518Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 21957
