[Job]
name = "flow"

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-13T09:35:11.012018Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 5026

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-13T09:35:11.017169Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 544196

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-13T09:35:11.561516Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3852

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-13T09:35:11.565385Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3477

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-13T09:35:11.569182Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3343

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-13T09:35:11.57254Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3365

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-13T09:35:11.575925Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 4342

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-13T09:35:11.580283Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 10249

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-13T09:35:11.59055Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 10948

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-13T09:35:11.601517Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 31678
