[Job]
name = "flow"

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T06:18:53.757942Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 5775

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T06:18:53.763839Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3307351

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T06:18:57.071344Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3820

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T06:18:57.075176Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3299

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T06:18:57.078663Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 2946

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T06:18:57.081614Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3159

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T06:18:57.084783Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3265

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T06:18:57.088055Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 6255

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T06:18:57.094322Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 7006

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-18T06:18:57.10134Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 11623
