[Job]
name = "flow"

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-19T02:05:01.972944Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 5392

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-19T02:05:01.978431Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 120397

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-19T02:05:02.098947Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3997

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-19T02:05:02.102952Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3371

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-19T02:05:02.106544Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3103

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-19T02:05:02.109655Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3156

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-19T02:05:02.112819Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3617

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-19T02:05:02.116444Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 22379

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-19T02:05:02.138836Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 6548

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-19T02:05:02.145396Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 10148
