[Job]
name = "flow"

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-19T07:02:12.075524Z"
stdout = "[510] no val: mkdir -p __NO[ENV_RUN]__"

[Job.tasks.result.Ok]
running_time = 209

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-19T07:02:12.075819Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 200924

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-19T07:02:12.276847Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 4366

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-19T07:02:12.28123Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3582

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-19T07:02:12.285045Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 4245

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-19T07:02:12.289307Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 4126

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-19T07:02:12.293443Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 4078

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-19T07:02:12.297527Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 10498

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-19T07:02:12.308037Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 12267

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-19T07:02:12.320318Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 34316
