[Job]
name = "flow"

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-12T07:00:45.055509Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 5546

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-12T07:00:45.061151Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 353560

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-12T07:00:45.414825Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3981

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-12T07:00:45.418814Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3623

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-12T07:00:45.422672Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3696

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-12T07:00:45.426384Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3435

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-12T07:00:45.429828Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3641

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-12T07:00:45.433476Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 12300

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-12T07:00:45.445787Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 22951

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-12T07:00:45.468751Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 49474
