[Job]
name = "flow"

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-13T09:33:04.912218Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 5264

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-13T09:33:04.917768Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 1005192

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-13T09:33:05.923116Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3456

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-13T09:33:05.926589Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3022

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-13T09:33:05.929941Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3452

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-13T09:33:05.933412Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3719

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-13T09:33:05.937148Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 4385

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-13T09:33:05.941551Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 10865

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-13T09:33:05.952435Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 11036

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-13T09:33:05.963488Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 31212
