[Job]
name = "flow"

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-19T07:40:38.22682Z"
stdout = """
[510] cmd err : 128,fatal: tag 'v0.7.4' already exists
"""

[Job.tasks.result.Ok]
running_time = 13909

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-19T07:40:38.24074Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3445484
