[Job]
name = "flow"

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-19T07:41:49.565403Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 14991

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-19T07:41:49.580406Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3781263
