[Job]
name = "flow"

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T04:00:51.28113Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 4933

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T04:00:51.286222Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 1156833

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T04:00:52.443169Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 15257

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T04:00:52.458438Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3397

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T04:00:52.462067Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3217

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T04:00:52.46529Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3192

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T04:00:52.468491Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 8014

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T04:00:52.476519Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 23193

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T04:00:52.499725Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 25648

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-17T04:00:52.525385Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 25762
