[Job]
name = "flow"

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-13T06:04:33.496448Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 5018

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-13T06:04:33.502057Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3655842

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-13T06:04:37.158371Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 4360

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-13T06:04:37.162755Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3083

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-13T06:04:37.166899Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3432

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-13T06:04:37.170347Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3181

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-13T06:04:37.173541Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 3872

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-13T06:04:37.17743Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 24176

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-13T06:04:37.201628Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 15977

[[Job.tasks]]
name = "gx.cmd"
begin = "2025-06-13T06:04:37.217629Z"
stdout = ""

[Job.tasks.result.Ok]
running_time = 21401
